name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
      env:
        DOTNET_CLI_HOME: /tmp
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Checkout Source Repository
        uses: actions/checkout@v6
        with:
          repository: 'parintorn0/ImagesViewer'
          ref: 'main'
          token: ${{ secrets.SOURCE_TOKEN }}
          path: 'ImagesViewer'

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup Dotnet 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.103'

      - name: Build Flatpak Repository
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: io.github.parintorn0.ImagesViewer.Carousel.yml
          build-bundle: false
          gpg-sign: ${{ steps.import_gpg.outputs.keyid }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build Flatpak Repository
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: io.github.parintorn0.ImagesViewer.Vertical.yml
          build-bundle: false
          gpg-sign: ${{ steps.import_gpg.outputs.keyid }}
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      
      - name: Update Flatpak Repository
        run: flatpak build-update-repo --gpg-sign=${GPG_KEY_ID} --generate-static-deltas --prune repo
        env:
          GPG_KEY_ID: ${{ steps.import_gpg.outputs.keyid }}

      - name: Upload Flatpak Repository Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          retention-days: 1
          path: repo/

  deploy:
    needs: build
    if: success()
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
